version: '3.8'
services:
  client:
    build:
      context: ./client
    volumes:
      - ./client:/app
    ports:
      - "19000:19000"

  server:
    build:
      context: ./server
    volumes:
      - ./server:/app
    ports:
      - "3000:3000"  # API用ポート
